# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
publish:
    stage: deploy
    image: ubuntu
    before_script:
        - apt-get update && apt-get install --assume-yes openssl ca-certificates python python-dev python-pip git snapd
        - snap install hugo --channel=extended
        - pip install awscli --upgrade
    script:
        - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
        - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
        - git submodule update --progress --init --recursive -- "themes/hugo-theme-learn"
        - hugo
        - aws s3 cp ./public/ s3://acceleratxr.io/ --recursive
