# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
publish:
    stage: deploy
    image: node:lts
    script:
        - apt update && apt install --assume-yes hugo openssl ca-certificates python python-dev python-pip
        - pip install awscli --upgrade
        - hugo
        - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
        - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
        - $(aws ecr get-login --no-include-email --region $AWS_REGION)
        - aws s3 cp ./public/ s3://acceleratxr.io/
