# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
publish:
    stage: deploy
    image: node:lts
    before_script:
        - apt update && apt install --assume-yes hugo openssl ca-certificates python python-dev python-pip git
        - pip install awscli --upgrade
    script:
        - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
        - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
        - pushd themes/hugo-theme-learn; git pull; popd
        - hugo
        - aws s3 cp ./public/ s3://acceleratxr.io/ --recursive
