version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: '3.10'

python:
  install:
    - requirements: requirements.txt

sphinx:
  builder: html
  configuration: docs/source/conf.py
  fail_on_warning: false
