version: 2

build:
  os: ubuntu-lts-latest
  tools:
    python: '3.10'
  jobs:
    pre_build:
      - |
        # Inject the GitLab access token into repository URLs if set
        # This is only useful for private repos on a free test account
        if [ -n "$GITLAB_ACCESS_TOKEN" ]; then
          echo "Injecting GitLab access token into the repository URL..."
          git config --global url."https://oauth2:$GITLAB_ACCESS_TOKEN@gitlab.acceleratxr.com/".insteadOf "https://gitlab.acceleratxr.com/"
        else
          echo "GITLAB_ACCESS_TOKEN is not set. Skipping access token injection."
        fi

python:
  install:
    - requirements: requirements.txt

sphinx:
  builder: html
  configuration: source/conf.py
  fail_on_warning: false  # TODO: Set this to true after fixing all warnings
