build:
  os: ubuntu-lts-latest
  tools:
    python: '3.10'
python:
  install:
  - requirements: requirements.txt
sphinx:
  builder: html
  configuration: source/conf.py
version: 2
versions:
  only:
  - 2024.07.0-TEST
  - 2024.06.0-TEST
