####################################################################
# (!) Currently, we don't need to use this since we're hosting with
#     `.readthedocs`.
#
# However, if we ever wanted to self-host or add anything fancy,
# Use this file as a template!
####################################################################
# Define the stages of the CI/CD pipeline
stages:
  - prepare   # Stage to prepare the environment
  - build     # Stage to build the documentation
  - deploy    # Stage to deploy the built documentation

# Define variables to be used in the pipeline
variables:
  SPHINXOPTS: "-n -W --keep-going"  # Options for sphinx-build
  MANIFEST_FILE: "repo_manifest.yml"  # Path to the manifest file

# Commands to run before the main script in each job
before_script:
  - apt-get update -y   # Update package list
  - apt-get install -y python3-pip   # Install pip for Python 3
  - pip3 install -r requirements.txt   # Install Python dependencies from requirements.txt

## Job to prepare the environment
#prepare:
#  stage: prepare
#  script:
#    - python3 tools/rtd_generator_from_manifest.py $MANIFEST_FILE   # Generate .readthedocs.yaml based on manifest

# Job to build the latest version of the documentation
build_latest:
  stage: build   # Assign this job to the 'build' stage
  script:
    - sphinx-build -b html source build/html   # Build the documentation using Sphinx
  only:
    - master  # Only run this job on the 'master' branch
    - dylan/test/mock-latest  # Only run this job on the 'mock-latest' branch (great for testing)
    - latest  # Also run on the 'latest' branch if exists

# Job to deploy the latest version of the documentation
deploy_latest:
  stage: deploy   # Assign this job to the 'deploy' stage
  script:
    - echo "Deploying latest documentation..."   # Echo a message for visibility
    # Add your deployment steps here, e.g., rsync, scp, or commit to a deployment branch
  only:
    - master   # Only run this job on the 'master' branch
    - latest   # Also run on the 'latest' branch if exists

# Job to build the 2024.1 version of the documentation
build_2024_1:
  stage: build   # Assign this job to the 'build' stage
  script:
    - sphinx-build -b html source build/html   # Build the documentation using Sphinx
  only:
    - 2024.1   # Only run this job on the '2024.1' branch

# Job to deploy the 2024.1 version of the documentation
deploy_2024_1:
  stage: deploy   # Assign this job to the 'deploy' stage
  script:
    - echo "Deploying 2024.1 documentation..."   # Echo a message for visibility
    # Add your deployment steps here
  only:
    - 2024.1   # Only run this job on the '2024.1' branch
