services:
    base:
        image: ${NAME}/base:${TAG}
        build:
            context: ..
            dockerfile: docker/Dockerfile.base
            args:
                FROM_IMAGE: ${FROM_IMAGE}
                WORKDIR: ${WORK_DIR}
                BASE_DIR: ${BASE_DIR}

    sphinx:
        image: ${NAME}/sphinx:${TAG}
        depends_on:
            - base
        build:
            context: ..
            dockerfile: ./docker/Dockerfile.sphinx
            args:
                FROM_IMAGE: ${NAME}/base:${TAG}
                WORKDIR: ${WORK_DIR}
                BASE_DIR: ${BASE_DIR_SPHINX}
