ARG FROM_IMAGE=ubuntu:22.04
FROM ${FROM_IMAGE}

RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
    && apt-get install -y wget git rsync make python3.10 python3-pip \
    && apt-get autoremove -y && apt-get clean -y \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* \
    && ln -s /usr/bin/python3 /usr/bin/python

ARG WORKDIR=/app
WORKDIR ${WORKDIR}

ARG BASE_DIR=.
ADD ${BASE_DIR}/docs/extensions ./docs/extensions
