ARG FROM_IMAGE=base
FROM ${FROM_IMAGE}

RUN wget https://doxygen.nl/files/doxygen-1.12.0.linux.bin.tar.gz \
    && tar -xzvf doxygen-1.12.0.linux.bin.tar.gz \
    && rsync -a doxygen-1.12.0/bin/ /usr/local/bin/ \
    && rsync -a doxygen-1.12.0/man/ /usr/local/man/ \
    && rm -rf doxygen-1.12.0*

ARG WORKDIR=/app
WORKDIR ${WORKDIR}

ARG BASE_DIR=tools/template-doxygen
ADD ${BASE_DIR} .

WORKDIR ${WORKDIR}/docs
RUN make install

ENTRYPOINT [ "make" ]
CMD [ "doxygen" ]
