.build_docs_doxygen:
    stage: build
    image: docker:latest
    services:
        - docker:dind
    rules:
        - if: '$CI_MERGE_REQUEST_EVENT_TYPE == "merged_result" && ($CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH || $CI_COMMIT_BRANCH == "dev")'
          when: on_success
        - if: "$CI_MERGE_REQUEST_EVENT_TYPE == null"
          when: manual
    before_script:
        # Compose doxygen builder image
        - docker compose -f docs/docker/docker-compose.yml build
        - |
            git remote remove origin
            git remote add origin https://gitlab-ci-token:${XBE_PROJECT_TOKEN}@${CI_SERVER_URL#https://}/${CI_PROJECT_PATH}.git
            git config user.email "xbe@xsolla.com"
            git config user.name "XBE Automated"
            export GIT_TERMINAL_PROMPT=0
    script:
        #  Run make doxygen...
        - echo "Rebuilding doxygen output..."
        - |
            docker run --rm \
                -e PROJECT_URL="$CI_PROJECT_URL" \
                -e PROJECT_BRANCH="$CI_COMMIT_REF_NAME" \
                -e PROJECT_NAME="$CI_PROJECT_NAME" \
                -v "${CI_PROJECT_DIR}:/app" \
                xbe-docs/base \
                doxygen
        # Check for changes after the first command...
        # If changed, run make dummy with EXHALE=True
        - |
            if [ -n "$(git status --porcelain)" ]; then
                echo "Changes detected after doxygen build, running Exhale..."
                docker run --rm \
                    -e PROJECT_URL="$CI_PROJECT_URL" \
                    -e PROJECT_BRANCH="$CI_COMMIT_REF_NAME" \
                    -e PROJECT_NAME="$CI_PROJECT_NAME" \
                    -v "${CI_PROJECT_DIR}:/app" \
                    xbe-docs/base \
                    dummy EXHALE=True
                git add .
                git commit -m "docs: rebuild documentation [skip ci]"
                git push origin HEAD:${CI_COMMIT_REF_NAME}
            else
                echo "No doxygen changes detected, skipping API doc rebuild."
            fi
